apiVersion: v1
kind: Service
metadata:
  name: mario-service
spec:
  type: LoadBalancer  # Cria um Load Balancer na AWS (expõe o serviço na internet)
  selector:
    app: mario  # Conecta este service aos pods com label "app: mario"
  ports:
  - protocol: TCP
    port: 80        # Porta externa (acesso via internet)
    targetPort: 80  # Porta do container (onde o jogo está rodando)
